# Generated by Django 2.1.5 on 2019-03-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penpalz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='avglvl',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prof',
            name='level',
            field=models.IntegerField(),
        ),
    ]
