# Generated by Django 2.1.5 on 2019-04-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penpalz_app', '0002_auto_20190331_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lang',
            name='avglvl',
        ),
    ]
