# Generated by Django 2.1.5 on 2019-04-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penpalz_app', '0003_remove_lang_avglvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='prof_check',
            field=models.IntegerField(default=0),
        ),
    ]
