# Generated by Django 2.1.5 on 2019-04-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penpalz_app', '0004_message_prof_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='prof_check',
        ),
    ]
